### ISSUE TITLE
It crashes with node 5

### ISSUE THREAD

**Issue by josepot** [mattcg/socks5-http-client#13]
I think that one of your dependencies ([socks5-client](https://github.com/mattcg/socks5-client)) has some issues with the latest stable version of node.

With node 5 I get the following error (that I don't get with the previous versions of node):

```
_http_outgoing.js:657
  socket.cork();
         ^

TypeError: socket.cork is not a function
    at ClientRequest._flushOutput (_http_outgoing.js:657:10)
    at ClientRequest.OutgoingMessage._flush (_http_outgoing.js:636:16)
    at _http_client.js:154:10
    at Socks5ClientSocket.callSocketMethod (_http_client.js:519:7)
    at Socks5ClientSocket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socks5ClientSocket.emit (events.js:166:7)
    at Socks5ClientSocket.handleSocksConnectToHost (/Users/xxxxx/Projects/xxxxx/node_modules/socks5-client/lib/Socks5ClientSocket.js:133:7)
    at /Users/xxxxx/Projects/xxxxx/node_modules/socks5-client/lib/Socks5ClientSocket.js:141:9
    at Socket.<anonymous> (/Users/xxxxx/Projects/xxxxx/node_modules/socks5-client/lib/Socks5ClientSocket.js:224:4)
```

**Comment by mattcg** [comment]
Try running `npm update`. This was fixed in v1.1.2.

**Comment by josepot** [comment]
Hi @mattcg,

I have already tried and I still have the same issue. I've created [this repo](https://github.com/josepot/socks5-issue-poc) so that you can reproduce the issue.

The only thing that the repo has is a `package.json` file with the following dependencies:

```
  "dependencies": {
    "request": "^2.65.0",
    "socks5-http-client": "^1.0.1"
  }
```

and a `index.js` file that looks like this:

```
'use strict';

var request = require('request');
var Agent = require('socks5-http-client/lib/Agent');

request({
    url: 'http://en.wikipedia.org/wiki/SOCKS',
    agentClass: Agent,
    agentOptions: {
        socksHost: '195.154.216.160',
        socksPort: 60088
    }
}, function(err, res) {
    console.log(err || res.body);
});
```

In order to reproduce the issue just do this:

```
git clone https://github.com/josepot/socks5-issue-poc.git
cd socks5-issue-poc
nvm use v5 # I'm using nvm so that I can try it with different version of node. If you have the latest version of node then you obviously won't need to run this ;)
npm install
node index.js
```

And that should give you the same error that I'm getting.

One thing that I've noticed though is that at this point the installed version of the `socks5-client` package is v1.0.0. You can confirm this by running the following command:

```
grep version node_modules/socks5-client/package.json
```

This is happening because of the [settings of the package.json of this project](https://github.com/mattcg/socks5-http-client/blob/master/package.json#L23)
 
That's why I've created another branch named: `forcing-latest-socks5-client` where the only difference with the master branch is that I've added the following dependency to the `package.json`: 

```
"socks5-client": "^1.1.2"
```

so now, if you run:

```
git checkout forcing-latest-socks5-client
npm update
grep version node_modules/socks5-client/package.json
```

You will see that now we are actually using v1.1.2 of the `socks5-client` package. However, the error is still there, just run:

```
node index.js
```

and you will get the error anyways.

What's interesting though, is that if I switch to a previous version of node everything works just fine.

Thanks!

Josep

**Comment by josepot** [comment]
DA! I was actually not forcing anything, since this package was still using the old version of "socks5-client", the PR should fix it, though. Thanks!

Josep
